#!/usr/bin/env bash

rm -rf "/etc/systemd/system/${BUILD_NAME}.service"
rm -rf "/etc/ld.so.conf.d/${BUILD_NAME}.conf"

if [ "$(ls -A /etc/systemd/system/${BUILD_NAME}.service.d)" ]; then
  rm -rf "/etc/systemd/system/${BUILD_NAME}.service.d"
fi

if [ -s "/etc/default/${BUILD_NAME}" ]; then
  rm -rf "/etc/default/${BUILD_NAME}"
else
  echo "Default file '/etc/default/${BUILD_NAME}' not empty, so not removing."
fi

if getent passwd ${BUILD_NAME} >/dev/null; then
  userdel ${BUILD_NAME} || true
fi
