#!/usr/bin/env bash

if [[ -d "/usr/local/lib/${BUILD_NAME}" ]]; then
  mkdir -p /etc/ld.so.conf.d
  echo "/usr/local/lib/${BUILD_NAME}" | tee "/etc/ld.so.conf.d/${BUILD_NAME}.conf"
  if [[ -e /usr/sbin/ldconfig ]]; then
    /usr/sbin/ldconfig
  fi
fi

if ! getent passwd ${BUILD_NAME} >/dev/null; then
  useradd --system \
          --shell /sbin/nologin \
          --create-home \
          --home-dir /var/lib/${BUILD_NAME} \
          --comment "${BUILD_NAME} Service" \
          ${BUILD_NAME}  >/dev/null
fi

mkdir -p "/etc/systemd/system/${BUILD_NAME}.service.d"

cat > "/etc/systemd/system/${BUILD_NAME}.service" <<EOF
[Unit]
Description=Container ${BUILD_NAME}
Documentation=https://github.com/cloudnull/protocol-builds
Documentation=https://cloudnull.io
After=systemd-udev-settle.service
Wants=systemd-udev-settle.service

[Service]
User=${BUILD_NAME}
Group=${BUILD_NAME}
EnvironmentFile=-/etc/default/${BUILD_NAME}
ExecStart=${BUILD_EXEC}
KillMode=mixed
Restart=always
RestartSec=3
LimitNOFILE=infinity
CPUAccounting=true
IOAccounting=true
MemoryAccounting=true
TasksAccounting=true
Slice=${BUILD_NAME}.slice
TasksMax=16384

[Install]
WantedBy=multi-user.target
EOF

mkdir -p "/etc/default"

touch "/etc/default/${BUILD_NAME}"

/usr/bin/systemctl daemon-reload >/dev/null
